### ISSUE TITLE
Tried to use test patients from Synthia Project

### ISSUE THREAD

**Issue by rjcdoc** [Chinlinlee/Burni#2]
I was trying to use this with some test data generated by the [Synthea Project](https://github.com/synthetichealth/synthea), but I get this error message that I am having trouble resolving.

I have looked at the FHIR payload and con confirm that the patient resource is there.

```
Error: Patient validation failed: resourceType: Path `resourceType` is required.
    at ValidationError.inspect (/Users/xxxxx/Documents/Projects/Burni/node_modules/mongoose/lib/error/validation.js:48:26)
    at formatValue (internal/util/inspect.js:745:19)
    at inspect (internal/util/inspect.js:319:10)
    at formatWithOptionsInternal (internal/util/inspect.js:1979:40)
    at formatWithOptions (internal/util/inspect.js:1861:10)
    at console.value (internal/console/constructor.js:336:14)
    at console.warn (internal/console/constructor.js:369:61)
    at doInsertData (/Users/xxxxx/Documents/Projects/Burni/api/FHIRApiService/create.js:104:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/Users/xxxxxx/Documents/Projects/Burni/api/FHIRApiService/create.js:86:29)
    at async module.exports (/Users/xxxxx/Documents/Projects/Burni/api/FHIR/Patient/controller/postPatient.js:3:12) {
  errors: {
    resourceType: ValidatorError: Path `resourceType` is required.
        at validate (/Users/xxxxx/Documents/Projects/Burni/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/xxxxx/Documents/Projects/Burni/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/Users/xxxxx/Documents/Projects/Burni/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/xxxxx/Documents/Projects/Burni/node_modules/mongoose/lib/document.js:2567:18
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'resourceType',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Patient validation failed'
}
```

**Comment by cylien** [comment]
Synthea does not generate FHIR Patient resources by default. Could you provide the FHIR JSON for debugging?

**Comment by rjcdoc** [comment]
Here is the command I used to generate the test patient.
`./run_synthea -p 1 --exporter.fhir.export true --exporter.years_of_history 1`

[Mickey576_Grant908_d1b9d277-811b-7601-e240-ded05bdfcc53.json.txt](https://github.com/Chinlinlee/Burni/files/8105710/Mickey576_Grant908_d1b9d277-811b-7601-e240-ded05bdfcc53.json.txt)

**Comment by Chinlinlee** [comment]
@rjcdoc
We currently do not support the `Bundle-Transaction` operation.
**The error shows you may be missing the `resourceType` in JSON.**
I copy the JSON of first patient resource in your file, and it gets a successful response.
- The patient resource in your file
```JSON
{
    "resourceType": "Patient",
    "id": "d1b9d277-811b-7601-e240-ded05bdfcc53",
    "meta": {
        "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        ]
    },
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: master-branch-latest\n .   Person seed: 5508974213412284240  Population seed: 1645319997296</div>"
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2106-3",
                        "display": "White"
                    }
                },
                {
                    "url": "text",
                    "valueString": "White"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Not Hispanic or Latino"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Glayds212 Schroeder447"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "M"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Boston",
                "state": "Massachusetts",
                "country": "US"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 0.0
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 10.0
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "d1b9d277-811b-7601-e240-ded05bdfcc53"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "d1b9d277-811b-7601-e240-ded05bdfcc53"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-31-6644"
        }
    ],
    "name": [
        {
            "use": "official",
            "family": "Grant908",
            "given": [
                "Mickey576"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "555-585-8132",
            "use": "home"
        }
    ],
    "gender": "male",
    "birthDate": "2011-11-23",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 42.32409919752856
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.01230088076522
                        }
                    ]
                }
            ],
            "line": [
                "363 Legros Viaduct Suite 25"
            ],
            "city": "Winthrop",
            "state": "MA",
            "postalCode": "02152",
            "country": "US"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "Never Married"
            }
        ],
        "text": "Never Married"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "en-US",
                        "display": "English"
                    }
                ],
                "text": "English"
            }
        }
    ]
}
```
- The response:
```JSON
{
    "resourceType": "Patient",
    "id": "1e7f0238-389a-4c2a-9dbb-c419848f04fd",
    "meta": {
        "profile": [
            "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        ],
        "versionId": "1",
        "lastUpdated": "2022-02-21T03:37:08.979+00:00"
    },
    "extension": [
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2106-3",
                        "display": "White"
                    }
                },
                {
                    "url": "text",
                    "valueString": "White"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
            "extension": [
                {
                    "url": "ombCategory",
                    "valueCoding": {
                        "system": "urn:oid:2.16.840.1.113883.6.238",
                        "code": "2186-5",
                        "display": "Not Hispanic or Latino"
                    }
                },
                {
                    "url": "text",
                    "valueString": "Not Hispanic or Latino"
                }
            ]
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
            "valueString": "Glayds212 Schroeder447"
        },
        {
            "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
            "valueCode": "M"
        },
        {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
            "valueAddress": {
                "city": "Boston",
                "state": "Massachusetts",
                "country": "US"
            }
        },
        {
            "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
            "valueDecimal": 0
        },
        {
            "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
            "valueDecimal": 10
        }
    ],
    "identifier": [
        {
            "system": "https://github.com/synthetichealth/synthea",
            "value": "d1b9d277-811b-7601-e240-ded05bdfcc53"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "MR",
                        "display": "Medical Record Number"
                    }
                ],
                "text": "Medical Record Number"
            },
            "system": "http://hospital.smarthealthit.org",
            "value": "d1b9d277-811b-7601-e240-ded05bdfcc53"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "SS",
                        "display": "Social Security Number"
                    }
                ],
                "text": "Social Security Number"
            },
            "system": "http://hl7.org/fhir/sid/us-ssn",
            "value": "999-31-6644"
        }
    ],
    "name": [
        {
            "use": "official",
            "family": "Grant908",
            "given": [
                "Mickey576"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "555-585-8132",
            "use": "home"
        }
    ],
    "gender": "male",
    "birthDate": "2011-11-23",
    "address": [
        {
            "extension": [
                {
                    "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
                    "extension": [
                        {
                            "url": "latitude",
                            "valueDecimal": 42.32409919752856
                        },
                        {
                            "url": "longitude",
                            "valueDecimal": -71.01230088076522
                        }
                    ]
                }
            ],
            "line": [
                "363 Legros Viaduct Suite 25"
            ],
            "city": "Winthrop",
            "state": "MA",
            "postalCode": "02152",
            "country": "US"
        }
    ],
    "maritalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
                "code": "S",
                "display": "Never Married"
            }
        ],
        "text": "Never Married"
    },
    "multipleBirthBoolean": false,
    "communication": [
        {
            "language": {
                "coding": [
                    {
                        "system": "urn:ietf:bcp:47",
                        "code": "en-US",
                        "display": "English"
                    }
                ],
                "text": "English"
            }
        }
    ]
}
```
